config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
    root to: 'items#index'
    resources :items do
      resources :orders, only:[:index, :create, :order]
      post 'order', on: :member
      # resources :items, only: :order do
      # post 'order', on: :member
      resources :comments, only: :create
    end
  resources :users, only:[:show, :edit, :update]
  resources :cards, only: [:new, :create]

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates :customer_token, presence: true
  validates :card_token, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    card = Card.where(user_id: current_user.id)
    if card.present?
      redirect_to users_show_path
    end

  end

  def create
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] # 環境変数を読み込む
    customer = Payjp::Customer.create(
    description: 'test', # テストカードであることを説明
    card: params[:card_token] # 登録しようとしているカード情報
    )
    card = Card.new( # トークン化されたカード情報を保存する
      card_token: params[:card_token], # カードトークン
      customer_token: customer.id, # 顧客トークン
      user_id: current_user.id # ログインしているユーザー
    )
  
    if card.save
      redirect_to root_path
    else
        redirect_to action: "new" # カード登録画面
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.erb
<%= render "shared/second-header"%>
<div class ="CardPage">
  <%= form_with  url: cards_path, id: 'charge-form', class: 'card-all',local: true do |f| %>
    <div class = "CardPage-main">
     <div class = "card-num-zorn">
      <div class = "Ragistration-form">
        <h1 class="Card-Ragistration">
            カード登録
        </h1>
        <br>
      </div>
      <div class='card-num'>
        <%= f.label :number, "【カード番号】" %>
        <span class="indispensable">必須</span>
        <%= f.text_field :number, class:"input-default", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
           <%= image_tag 'card-mastercard.gif', class: 'card-logo'%> 
           <%= image_tag 'card-jcb.gif', class: 'card-logo'%> 
           <%= image_tag 'card-amex.gif', class: 'card-logo'%> 
         </div>  
      </div>
      <div class='cvc-form'>
        <%= f.label :cvc ,"【ＣＶＣ】" %>
        <span class="indispensable">必須</span>
        <%= f.text_field :cvc, class:"input-default", placeholder:"カード背面にある3桁の番号", maxlength:"4" %>
      </div>
      <div class ="days-card">
         <p>【有効期限】</p> 
         <span class="indispensable">必須</span>
        <div class='input-expiration-date-wrap'>
         <h1 class = "input-expiration-date-left">
           <%= f.select :exp_month, 1..12, {include_blank: "---"}, class: "left" %>
             <p>月</p>
         </h1>
         <h2 class = "input-expiration-date-right" >
           <%= f.select :exp_year, 20..25, {include_blank: "---"}, class: "right" %>
             <p>年</p>
         </h2>
       </div>
      </div>
    </div>
    <div class = "card-btn-form">
      <div class ="card-button">
        <%= f.submit "登録する" %> 
      </div>
    </div>
  </div>
 <% end %>
</div>
      
   

<footer class="card-sell-footer">
    <ul class="menu-card">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="link">
      ©︎Furima,Inc.
    </p>
</footer>